# mysql datasource
spring.datasource.url: jdbc:mysql://127.0.0.1/wiredcraft?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username: user
spring.datasource.password: password
